using System.Collections.Generic;

namespace RobotControllerClient.Protocol
{
    public static class ErrorCodes
    {
        private static readonly Dictionary<string, string> Map = new Dictionary<string, string>
        {
            { "00001", "Liveman Error" },
            { "00002", "There is no wafer" },
            { "00003", "There is a wafer" },
            { "00004", "Check operation mode" },
            { "00005", "Home all is not done" },
            { "00006", "Controller is not ready" },
            { "00007", "Station or slot number is wrong" },
            { "00008", "Command is not correct" },
            { "00009", "E-Stop/User IO is disconnected" },
            { "00010", "Station is not match with arm" },
            { "00011", "Goto is not do after arm changed" },
            { "00012", "Error is not Cleared" },
            { "00100", "Initialization is failed, Reboot Robot Controller" },
            { "00101", "Host COM was not Initialized" },
            { "00102", "TP COM was not Initialized" },
            { "00103", "Check CDA Pressure" },
            { "10001", "RA is not retracted" },
            { "10002", "RB is not retracted" },
            { "10005", "Check extend interlock" },
            { "10009", "Check sensor signal" },
            { "10010", "Drive is not Enabled" },
            { "10012", "Error Clear is failed" },
            { "2x000", "Check motion board connection with drive" },
            { "2x011", "Control power supply under voltage protection" },
            { "2x012", "Overvoltage protection" },
            { "2x013", "Main power supply under voltage protection" },
            { "2x014", "Over current protection" },
            { "2x015", "Over-heat protection" },
            { "2x016", "Over-load protection" },
            { "2x018", "Over regeneration load protection" },
            { "2x021", "Encoder communication error protection" },
            { "2x023", "Encoder communication data error protection" },
            { "2x024", "Position deviation excess protection" },
            { "2x025", "Hybrid deviation excess error protection" },
            { "2x026", "Over-speed protection" },
            { "2x027", "Electronic gear error protection" },
            { "2x028", "External scale communication data error protection" },
            { "2x029", "Deviation counter overflow protection" },
            { "2x034", "Software limit protection" },
            { "2x035", "External scale communication error protection" },
            { "2x036", "EEPROM parameter error protection" },
            { "2x037", "EEPROM check code error protection" },
            { "2x038", "Over-travel inhibit input protection" },
            { "2x039", "Analog input excess protection" },
            { "2x040", "Absolute system down error protection" },
            { "2x041", "Absolute counter over error protection" },
            { "2x042", "Absolute over-speed error protection" },
            { "2x044", "Absolute single turn counter error protection" },
            { "2x045", "Absolute multi-turn counter error protection" },
            { "2x047", "Absolute status error protection" },
            { "2x048", "Encoder Z-phase error protection" },
            { "2x049", "Encoder CS signal error protection" },
            { "2x050", "External scale status 0 error protection" },
            { "2x051", "External scale status 1 error protection" },
            { "2x052", "External scale status 2 error protection" },
            { "2x053", "External scale status 3 error protection" },
            { "2x054", "External scale status 4 error protection" },
            { "2x055", "External scale status 5 error protection" },
            { "2x065", "CCWTL input excess protection" },
            { "2x066", "CWTL input excess protection" },
            { "2x095", "Motor automatic recognition error protection" },
            { "2x100", "Motor Power on is failed" },
            { "2x101", "Over Time Error" },
            { "2x102", "Check Reference Position" },
            { "2x103", "Check Current Position" },
            { "2x104", "Motor Power is not On" },
            { "2x105", "Check Extend Interlock IO" },
            { "2x106", "Check Wafer Presence" },
            { "2x107", "Check Current Position & Encoder value" },
            { "2x108", "Home Define is failed, Check serial cable with drive" },
            { "2x109", "Check Grip Status" },
            { "2x120", "Negative end limit protection" },
            { "2x121", "Positive end limit protection" },
            { "4x100", "Gripper is not Move to UnGrip position" },
            { "4x101", "Gripper is not Move to Grip position" },
            { "4x106", "Check Wafer Presence" },
            { "4x109", "Check Grip Status" },
            { "4x130", "Place Moving Check Wafer Present" },
            { "4x131", "Place Done Check Wafer" },
            { "4x140", "Pick Moving Check Wafer Present" },
            { "4x141", "Pick Done Check Wafer" },
            { "4x200", "Check Wafer Error : Pick Start" },
            { "4x201", "Check Wafer Error : Pick Extend" },
            { "4x210", "Check Wafer Error : Place Start" },
            { "4x211", "Check Wafer Error : Place Extend" },
            { "4x400", "UnGrip Fail : Check Sensor Please" },
            { "4x401", "Grip Fail : Check Sensor Please" },
            { "5x001", "Illegal command" },
            { "5x002", "Wrong number of stage" },
            { "5x003", "Wrong number of arm" },
            { "5x004", "Wrong number of slot" },
            { "5x005", "Illegal speed range" },
            { "5x006", "Wrong number of robot axis" },
            { "5x007", "Invalid value of axis location" },
            { "5x008", "Illegal argument value" },
            { "5x010", "Invalid argument type" },
            { "5x011", "Invalid robot number" },
            { "5x012", "Invalid value of pitch" },
            { "5x013", "Invalid value of up stroke" },
            { "5x014", "Invalid value of down stroke" },
            { "5x015", "Invalid value of total number of slot" },
            { "5x016", "Invalid value of mapping speed" },
            { "5x017", "Invalid value of reference thickness" },
            { "5x018", "Invalid value of thickness margin" },
            { "5x019", "Invalid value of existence margin" },
            { "5x020", "Invalid robot type number" },
            { "5x021", "Invalid arm type number" },
            { "5x022", "Invalid value of total number of axis" },
            { "5x023", "Invalid grip type number" },
            { "5x024", "Invalid value of mapping sensor" },
            { "5x025", "Invalid value of traverse axis" },
            { "5x026", "Invalid value of arm location" },
            { "5x027", "Invalid value of On/Off" },
            { "5x028", "Invalid signal number" },
            { "5x029", "Invalid value of delay time" },
            { "5x031", "Invalid value of retry count on error" },
            { "5x033", "Invalid value of arm distance" },
            { "5x034", "Invalid value of protruded material detect start position" },
            { "5x035", "Invalid value of protruded material detect count" },
            { "5x036", "Invalid value of clearance" },
            { "5x037", "Invalid value of material state" },
            { "5x038", "Invalid value of mode" },
            { "5x039", "Invalid value of offset" },
            { "5x041", "Invalid value of aligner argument" },
            { "5x042", "Aligner communication time-out error" },
            { "5x043", "Invalid value of IO" },
            { "5x051", "Data read busy" },
            { "5x052", "Data write busy" },
            { "5x053", "Robot control busy" },
            { "5x054", "Aligner busy" },
            { "5x055", "Ardiono busy*" },
            { "5x061", "Flash Busy" },
            { "5x081", "Stage info file load error" },
            { "5x180", "File Read Error" },
            { "5x181", "Pattern file load error" },
            { "5x182", "Profile file load error" },
            { "5x184", "Stage info file load error" },
            { "5x185", "Robot type file load error" },
            { "5x186", "Option file load error" },
            { "5x201", "Robot is busy" },
            { "5x202", "Servo power is off" },
            { "5x203", "On E-Stop" },
            { "5x204", "Robot is paused" },
            { "5x205", "Robot is not paused" },
            { "5x206", "Robot is not executing command" },
            { "5x207", "Robot is stopped" },
            { "5x208", "Robot has an error" },
            { "5x209", "Servo power is on" },
            { "5x211", "Robot paused by I/O signal" },
            { "5x212", "Robot is manual mode" },
            { "5x213", "Robot is auto mode" },
            { "5x215", "Robot Stopped by Extend Signal Disable" },
            { "5x222", "Error on material status during mapping" },
            { "5x224", "Material detected before mapping" },
            { "5x225", "Station does not match previous one" },
            { "5x232", "Map scan data does not exist" },
            { "5x233", "Map scan data does not Match" },
            { "5x234", "Map scan data detected over slot" },
            { "5x241", "Robot hand is already flipped" },
            { "5x242", "Robot hand is not flipped" },
            { "5x243", "Robot can't flip this position" },
            { "5x261", "Aligner module is not connected" },
            { "5x262", "Aligner connect fail" },
            { "5x271", "Need re-set variable pitch" },
            { "5x291", "Need stage teaching" },
            { "5x292", "Need stage parameter config" },
            { "5x293", "This stage is flipped location" },
            { "5x294", "This stage is not flipped location" },
            { "5x295", "Clearance value is set to be wrong" },
            { "5x301", "Handling material before GETFROM" },
            { "5x302", "Not Handling material before PUTINTO" },
            { "5x303", "Not Handling material after GETFROM" },
            { "5x304", "Handling material before PUTINTO" },
            { "5x307", "Illegal Check sensor status" },
            { "5x312", "Current robot position is dangerous" },
            { "5x350", "Slave Servo ON Timeout" },
            { "5x401", "Data read error" },
            { "5x402", "Writing host serial port time-out error" },
            { "6x1xx", "Robot Related Errors" },
            { "6x2xx", "Standard System Errors" },
            { "6x3xx", "Hardware Device Related Errors" },
            { "6x4xx", "Configuration Parameter Database, Datalogger, and CPU Monitor Errors" },
            { "6x500~", "Input and Output Errors" },
            { "6x550~", "Controller Errors" },
            { "6x6xx", "Network, Socket, and Communication Errors" },
            { "6x7xx,6x8xx", "Language Related Errors" },
            { "6x9xx", "Servo Related Errors" },
        };

        public static string Describe(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return null;
            }

            string trimmed = code.Trim();
            if (Map.ContainsKey(trimmed))
            {
                return Map[trimmed];
            }

            if (trimmed.Length == 5)
            {
                string masked = trimmed.Substring(0, 1) + "x" + trimmed.Substring(2);
                if (Map.ContainsKey(masked))
                {
                    return Map[masked];
                }
            }

            return null;
        }
    }
}
